# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.15
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/disaster37/check-yarn
    steps:
      - checkout
      - run: go test -v ./...
  build:
    docker:
      - image: circleci/golang:1.15
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/disaster37/check-yarn
    steps:
      - checkout
      - run: go build
  release:
    docker:
      - image: circleci/golang:1.15
        environment:
          - GO111MODULE: "on"
          - GITHUB_TOKEN: $GITHUB_TOKEN
          - CIRCLE_PROJECT_USERNAME: $CIRCLE_PROJECT_USERNAME
          - CIRCLE_PROJECT_REPONAME: $CIRCLE_PROJECT_REPONAME
          - CIRCLE_TAG: $CIRCLE_TAG
    working_directory: /go/src/github.com/disaster37/check-yarn
    steps:
      - checkout
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run: sed -i 's/app.Version := "develop"/app.Version := "$CIRCLE_TAG"/' main.go
      - run: gox -os="linux" -output "dist/check-yarn_{{.OS}}_{{.Arch}}"
      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG dist/
workflows:
  version: 2
  build-workflow:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - release:
          context: Github
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/